import { ThemeProvider, useTheme } from "@/providers/ThemeProvider";
import "./globals.css";
import { manrope,w98Font } from "./fonts";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/sections/Footer";
import { Toaster } from "@/components/ui/sonner";





export const metadata = {
  title: "Aqiel | Personal Portfolio",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${manrope.variable} ${w98Font.variable}`}>
      <body>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
